{{- if .Values.topics -}}
{{- $bootstrapServer := printf "%s-headless.%s.svc.%s:%d" (include "kafka.fullname" .) .Release.Namespace .Values.clusterDomain ( int .Values.headless.broker.port) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  {{- include "kafka.config.labels" . | nindent 4 }}
  name: {{ template "kafka.fullname" . }}-config
data:
  runtimeConfig.sh: |
    #!/bin/bash
    set -e
    cd /opt/kafka/bin

    until ./kafka-configs.sh --bootstrap-server {{ $bootstrapServer }} --entity-type topics --describe || (( count++ >= 6 ))
    do
      echo "Waiting for Kafka metadata quorum..."
      sleep 20
    done

    # expected='0,1,2,3,...,n,'
    # the trailing comma is significant
    expected='{{ until (int .Values.replicas) | join "," | trim }},'
    connected_brokers=''
    until [[ "$connected_brokers" == "$expected" ]]
    do
      echo "Waiting for all Kafka brokers to be available in metadata quorum..."
      ## NOTE: this command will fail because the container doesn't set up kafka data mount
      connected_brokers=$(kafka-metadata-shell --snapshot {{ .Values.persistence.mountPath }}/metadata/meta.properties --entity-type broker | \
        grep '"id"' | \
        awk -F ': ' '{print $2}' | \
        tr -d ',' | \
        sort | \
        tr '\n' ',' | \
        sed 's/,$//'
      )
      echo "Currently available brokers: $connected_brokers"
      echo "Expected brokers: $expected"
      sleep 20
    done

    echo "Applying runtime configuration using {{ .Values.image }}:{{ .Values.imageTag }}"
  {{- range $n, $topic := .Values.topics }}
    {{- if and $topic.partitions $topic.replicationFactor $topic.reassignPartitions }}
    cat << EOF > {{ $topic.name }}-increase-replication-factor.json
      {"version":1, "partitions":[
        {{- $partitions := (int $topic.partitions) }}
        {{- $replicas := (int $topic.replicationFactor) }}
        {{- range $i := until $partitions }}
          {"topic":"{{ $topic.name }}","partition":{{ $i }},"replicas":[{{- range $j := until $replicas }}{{ $j }}{{- if ne $j (sub $replicas 1) }},{{- end }}{{- end }}]}{{- if ne $i (sub $partitions 1) }},{{- end }}
        {{- end }}
      ]}
    EOF
    ./kafka-reassign-partitions.sh --bootstrap-server {{ $bootstrapServer }} --reassignment-json-file {{ $topic.name }}-increase-replication-factor.json --execute
    ./kafka-reassign-partitions.sh --bootstrap-server {{ $bootstrapServer }} --reassignment-json-file {{ $topic.name }}-increase-replication-factor.json --verify
    {{- else if and $topic.partitions $topic.replicationFactor }}
    ./kafka-topics.sh --bootstrap-server {{ $bootstrapServer }} --create --if-not-exists --force --topic {{ $topic.name }} --partitions {{ $topic.partitions }} --replication-factor {{ $topic.replicationFactor }}
    {{- else if $topic.partitions }}
    ./kafka-topics.sh --bootstrap-server {{ $bootstrapServer }} --alter --force --topic {{ $topic.name }} --partitions {{ $topic.partitions }} || true
    {{- end }}
    {{- if $topic.defaultConfig }}
    ./kafka-configs.sh --bootstrap-server {{ $bootstrapServer }} --entity-type topics --entity-name {{ $topic.name }} --alter --force --delete-config {{ nospace $topic.defaultConfig }} || true
    {{- end }}
    {{- if $topic.config }}
    ./kafka-configs.sh --bootstrap-server {{ $bootstrapServer }} --entity-type topics --entity-name {{ $topic.name }} --alter --force --add-config {{ nospace $topic.config }}
    {{- end }}
    ./kafka-configs.sh --bootstrap-server {{ $bootstrapServer }} --entity-type topics --entity-name {{ $topic.name }} --describe
    {{- if $topic.acls }}
      {{- range $a, $acl := $topic.acls }}
        {{ if and $acl.user $acl.operations }}
    ./kafka-acls.sh --bootstrap-server {{ $bootstrapServer }} --force --add --allow-principal User:{{ $acl.user }}{{- range $operation := $acl.operations }} --operation {{ $operation }} {{- end }} --topic {{ $topic.name }} {{ $topic.extraParams }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}
