{{ if and .Values.prometheus.kafka.enabled .Values.prometheus.operator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kafka.fullname" . }}-kafka-exporter
  namespace: {{ include "serviceMonitor.namespace" . }}
  labels:
    {{- include "kafka.monitor.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheus.operator.serviceMonitor.selector | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "kafka.monitor.matchLabels" . | nindent 6 }}
  endpoints:
  - port: kafka-exporter
    interval: {{ .Values.prometheus.kafka.interval }}
    {{- if .Values.prometheus.kafka.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheus.kafka.scrapeTimeout }}
    {{- end }}
    metricRelabelings:
    {{- toYaml .Values.prometheus.operator.serviceMonitor.metricRelabelings | nindent 6 }}
    relabelings:
    {{- toYaml .Values.prometheus.operator.serviceMonitor.relabelings | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
