apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
  labels:
  {{- include "kafka.broker.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
{{- if .Values.headless.annotations }}
{{ .Values.headless.annotations | toYaml | trimSuffix "\n" | indent 4 }}
{{- end }}
spec:
  ports:
  - name: broker-plaintext
    port: {{ .Values.headless.broker.plaintext.port }}
{{- if .Values.headless.broker.plaintext.targetPort }}
    targetPort: {{ .Values.headless.broker.plaintext.targetPort }}
{{- end }}
  - name: controller  
    port: {{ .Values.headless.controller.port }}
{{- if .Values.headless.controller.targetPort }}
    targetPort: {{ .Values.headless.controller.targetPort }}
{{- end }}
  - name: broker-ssl
    port: {{ .Values.headless.broker.ssl.port }}
{{- if .Values.headless.broker.ssl.targetPort }}
    targetPort: {{ .Values.headless.broker.ssl.targetPort }}
{{- end }}
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
  {{- include "kafka.broker.matchLabels" . | nindent 4 }}
